const COUNTRY_FLAG_ALIASES = {
  argentina: "ar",
  australia: "au",
  austria: "at",
  belgium: "be",
  brazil: "br",
  cameroon: "cm",
  canada: "ca",
  chile: "cl",
  china: "cn",
  colombia: "co",
  costa_rica: "cr",
  croatia: "hr",
  czech_republic: "cz",
  czechia: "cz",
  denmark: "dk",
  ecuador: "ec",
  egypt: "eg",
  england: "gb-eng",
  finland: "fi",
  france: "fr",
  germany: "de",
  ghana: "gh",
  greece: "gr",
  hungary: "hu",
  iceland: "is",
  india: "in",
  iran: "ir",
  iraq: "iq",
  ireland: "ie",
  israel: "il",
  italy: "it",
  ivory_coast: "ci",
  cote_d_ivoire: "ci",
  japan: "jp",
  korea_republic: "kr",
  south_korea: "kr",
  mexico: "mx",
  morocco: "ma",
  netherlands: "nl",
  new_zealand: "nz",
  nigeria: "ng",
  norway: "no",
  paraguay: "py",
  peru: "pe",
  poland: "pl",
  portugal: "pt",
  qatar: "qa",
  romania: "ro",
  saudi_arabia: "sa",
  scotland: "gb-sct",
  senegal: "sn",
  serbia: "rs",
  south_africa: "za",
  spain: "es",
  sweden: "se",
  switzerland: "ch",
  tunisia: "tn",
  turkey: "tr",
  turkiye: "tr",
  ukraine: "ua",
  united_arab_emirates: "ae",
  usa: "us",
  us: "us",
  united_states: "us",
  united_states_of_america: "us",
  uruguay: "uy",
  venezuela: "ve",
  wales: "gb-wls",
};

const FIFA_COUNTRY_CODES = {
  arg: "ar",
  aus: "au",
  aut: "at",
  bel: "be",
  bra: "br",
  can: "ca",
  chi: "cl",
  chn: "cn",
  civ: "ci",
  cmr: "cm",
  col: "co",
  crc: "cr",
  cro: "hr",
  cze: "cz",
  den: "dk",
  ecu: "ec",
  egy: "eg",
  eng: "gb-eng",
  esp: "es",
  fin: "fi",
  fra: "fr",
  ger: "de",
  gha: "gh",
  gre: "gr",
  hun: "hu",
  ind: "in",
  irl: "ie",
  irn: "ir",
  irq: "iq",
  isl: "is",
  isr: "il",
  ita: "it",
  jpn: "jp",
  kor: "kr",
  mar: "ma",
  mex: "mx",
  ned: "nl",
  nga: "ng",
  nor: "no",
  nzl: "nz",
  par: "py",
  per: "pe",
  pol: "pl",
  por: "pt",
  qat: "qa",
  rou: "ro",
  ksa: "sa",
  sco: "gb-sct",
  sen: "sn",
  srb: "rs",
  sui: "ch",
  swe: "se",
  tun: "tn",
  tur: "tr",
  uae: "ae",
  ukr: "ua",
  uru: "uy",
  usa: "us",
  ven: "ve",
  wal: "gb-wls",
  zaf: "za",
};

function normalizeCountryName(value) {
  return String(value || "")
    .trim()
    .toLowerCase()
    .replace(/&/g, "and")
    .replace(/[^a-z0-9]+/g, "_")
    .replace(/^_+|_+$/g, "");
}

export function getCountryFlagCode(teamName) {
  const normalized = normalizeCountryName(teamName);
  if (!normalized) return null;
  return COUNTRY_FLAG_ALIASES[normalized] || FIFA_COUNTRY_CODES[normalized] || null;
}

export function getCountryFlagUrl(teamName, size = 80) {
  const code = getCountryFlagCode(teamName);
  if (!code) return null;
  return `https://flagcdn.com/w${size}/${code}.png`;
}
