import { getCountryFlagUrl } from "@/lib/country-flags";

const CLUB_LOGO_BY_NAME = {
  austria_vienna: "/logos/Austria - Bundesliga/Austria Vienna.png",
  fc_blau_weiss_linz: "/logos/Austria - Bundesliga/FC Blau-Weiss Linz.png",
  grazer_ak_1902: "/logos/Austria - Bundesliga/Grazer AK 1902.png",
  lask: "/logos/Austria - Bundesliga/LASK.png",
  rapid_vienna: "/logos/Austria - Bundesliga/Rapid Vienna.png",
  red_bull_salzburg: "/logos/Austria - Bundesliga/Red Bull Salzburg.png",
  scr_altach: "/logos/Austria - Bundesliga/SCR Altach.png",
  sk_sturm_graz: "/logos/Austria - Bundesliga/SK Sturm Graz.png",
  sv_ried: "/logos/Austria - Bundesliga/SV Ried.png",
  tsv_hartberg: "/logos/Austria - Bundesliga/TSV Hartberg.png",
  wsg_tirol: "/logos/Austria - Bundesliga/WSG Tirol.png",
  wolfsberger_ac: "/logos/Austria - Bundesliga/Wolfsberger AC.png",
  cercle_brugge: "/logos/Belgium - Jupiler Pro League/Cercle Brugge.png",
  club_brugge_kv: "/logos/Belgium - Jupiler Pro League/Club Brugge KV.png",
  fcv_dender_eh: "/logos/Belgium - Jupiler Pro League/FCV Dender EH.png",
  kaa_gent: "/logos/Belgium - Jupiler Pro League/KAA Gent.png",
  krc_genk: "/logos/Belgium - Jupiler Pro League/KRC Genk.png",
  kv_mechelen: "/logos/Belgium - Jupiler Pro League/KV Mechelen.png",
  kvc_westerlo: "/logos/Belgium - Jupiler Pro League/KVC Westerlo.png",
  oud_heverlee_leuven: "/logos/Belgium - Jupiler Pro League/Oud-Heverlee Leuven.png",
  raal_la_louviere: "/logos/Belgium - Jupiler Pro League/RAAL La Louvière.png",
  rsc_anderlecht: "/logos/Belgium - Jupiler Pro League/RSC Anderlecht.png",
  royal_antwerp_fc: "/logos/Belgium - Jupiler Pro League/Royal Antwerp FC.png",
  royal_charleroi_sc: "/logos/Belgium - Jupiler Pro League/Royal Charleroi SC.png",
  sint_truidense_vv: "/logos/Belgium - Jupiler Pro League/Sint-Truidense VV.png",
  standard_liege: "/logos/Belgium - Jupiler Pro League/Standard Liège.png",
  union_saint_gilloise: "/logos/Belgium - Jupiler Pro League/Union Saint-Gilloise.png",
  zulte_waregem: "/logos/Belgium - Jupiler Pro League/Zulte Waregem.png",
  arda_kardzhali: "/logos/Bulgaria - efbet Liga/Arda Kardzhali.png",
  beroe_stara_zagora: "/logos/Bulgaria - efbet Liga/Beroe Stara Zagora.png",
  botev_plovdiv: "/logos/Bulgaria - efbet Liga/Botev Plovdiv.png",
  botev_vratsa: "/logos/Bulgaria - efbet Liga/Botev Vratsa.png",
  cska_1948: "/logos/Bulgaria - efbet Liga/CSKA 1948.png",
  cska_sofia: "/logos/Bulgaria - efbet Liga/CSKA-Sofia.png",
  cherno_more_varna: "/logos/Bulgaria - efbet Liga/Cherno More Varna.png",
  dobrudzha_dobrich: "/logos/Bulgaria - efbet Liga/Dobrudzha Dobrich.png",
  levski_sofia: "/logos/Bulgaria - efbet Liga/Levski Sofia.png",
  lokomotiv_plovdiv: "/logos/Bulgaria - efbet Liga/Lokomotiv Plovdiv.png",
  lokomotiv_sofia: "/logos/Bulgaria - efbet Liga/Lokomotiv Sofia.png",
  ludogorets_razgrad: "/logos/Bulgaria - efbet Liga/Ludogorets Razgrad.png",
  montana: "/logos/Bulgaria - efbet Liga/Montana.png",
  septemvri_sofia: "/logos/Bulgaria - efbet Liga/Septemvri Sofia.png",
  slavia_sofia: "/logos/Bulgaria - efbet Liga/Slavia Sofia.png",
  spartak_varna: "/logos/Bulgaria - efbet Liga/Spartak Varna.png",
  gnk_dinamo_zagreb: "/logos/Croatia - SuperSport HNL/GNK Dinamo Zagreb.png",
  hnk_gorica: "/logos/Croatia - SuperSport HNL/HNK Gorica.png",
  hnk_hajduk_split: "/logos/Croatia - SuperSport HNL/HNK Hajduk Split.png",
  hnk_rijeka: "/logos/Croatia - SuperSport HNL/HNK Rijeka.png",
  hnk_vukovar_1991: "/logos/Croatia - SuperSport HNL/HNK Vukovar 1991.png",
  nk_istra_1961: "/logos/Croatia - SuperSport HNL/NK Istra 1961.png",
  nk_lokomotiva_zagreb: "/logos/Croatia - SuperSport HNL/NK Lokomotiva Zagreb.png",
  nk_osijek: "/logos/Croatia - SuperSport HNL/NK Osijek.png",
  nk_varazdin: "/logos/Croatia - SuperSport HNL/NK Varazdin.png",
  slaven_belupo_koprivnica: "/logos/Croatia - SuperSport HNL/Slaven Belupo Koprivnica.png",
  "1_fc_slovacko": "/logos/Czech Republic - Chance Liga/1.FC Slovacko.png",
  ac_sparta_prague: "/logos/Czech Republic - Chance Liga/AC Sparta Prague.png",
  bohemians_prague_1905: "/logos/Czech Republic - Chance Liga/Bohemians Prague 1905.png",
  fc_banik_ostrava: "/logos/Czech Republic - Chance Liga/FC Banik Ostrava.png",
  fc_hradec_kralove: "/logos/Czech Republic - Chance Liga/FC Hradec Kralove.png",
  fc_slovan_liberec: "/logos/Czech Republic - Chance Liga/FC Slovan Liberec.png",
  fc_viktoria_plzen: "/logos/Czech Republic - Chance Liga/FC Viktoria Plzen.png",
  fc_zlin: "/logos/Czech Republic - Chance Liga/FC Zlin.png",
  fk_dukla_prague: "/logos/Czech Republic - Chance Liga/FK Dukla Prague.png",
  fk_jablonec: "/logos/Czech Republic - Chance Liga/FK Jablonec.png",
  fk_mlada_boleslav: "/logos/Czech Republic - Chance Liga/FK Mlada Boleslav.png",
  fk_pardubice: "/logos/Czech Republic - Chance Liga/FK Pardubice.png",
  fk_teplice: "/logos/Czech Republic - Chance Liga/FK Teplice.png",
  mfk_karvina: "/logos/Czech Republic - Chance Liga/MFK Karvina.png",
  sk_sigma_olomouc: "/logos/Czech Republic - Chance Liga/SK Sigma Olomouc.png",
  sk_slavia_prague: "/logos/Czech Republic - Chance Liga/SK Slavia Prague.png",
  aaruhus_gf: "/logos/Denmark - Superliga/Aarhus GF.png",
  brondby_if: "/logos/Denmark - Superliga/Bröndby IF.png",
  fc_copenhagen: "/logos/Denmark - Superliga/FC Copenhagen.png",
  fc_fredericia: "/logos/Denmark - Superliga/FC Fredericia.png",
  fc_midtjylland: "/logos/Denmark - Superliga/FC Midtjylland.png",
  fc_nordsjaelland: "/logos/Denmark - Superliga/FC Nordsjaelland.png",
  odense_boldklub: "/logos/Denmark - Superliga/Odense Boldklub.png",
  randers_fc: "/logos/Denmark - Superliga/Randers FC.png",
  silkeborg_if: "/logos/Denmark - Superliga/Silkeborg IF.png",
  sonderjyske: "/logos/Denmark - Superliga/Sönderjyske.png",
  vejle_boldklub: "/logos/Denmark - Superliga/Vejle Boldklub.png",
  viborg_ff: "/logos/Denmark - Superliga/Viborg FF.png",
  afc_bournemouth: "/logos/England - Premier League/AFC Bournemouth.png",
  arsenal_fc: "/logos/England - Premier League/Arsenal FC.png",
  aston_villa: "/logos/England - Premier League/Aston Villa.png",
  brentford_fc: "/logos/England - Premier League/Brentford FC.png",
  brighton_and_hove_albion: "/logos/England - Premier League/Brighton & Hove Albion.png",
  burnley_fc: "/logos/England - Premier League/Burnley FC.png",
  chelsea_fc: "/logos/England - Premier League/Chelsea FC.png",
  crystal_palace: "/logos/England - Premier League/Crystal Palace.png",
  everton_fc: "/logos/England - Premier League/Everton FC.png",
  fulham_fc: "/logos/England - Premier League/Fulham FC.png",
  leeds_united: "/logos/England - Premier League/Leeds United.png",
  liverpool_fc: "/logos/England - Premier League/Liverpool FC.png",
  manchester_city: "/logos/England - Premier League/Manchester City.png",
  manchester_united: "/logos/England - Premier League/Manchester United.png",
  newcastle_united: "/logos/England - Premier League/Newcastle United.png",
  nottingham_forest: "/logos/England - Premier League/Nottingham Forest.png",
  sunderland_afc: "/logos/England - Premier League/Sunderland AFC.png",
  tottenham_hotspur: "/logos/England - Premier League/Tottenham Hotspur.png",
  west_ham_united: "/logos/England - Premier League/West Ham United.png",
  wolverhampton_wanderers: "/logos/England - Premier League/Wolverhampton Wanderers.png",
  aj_auxerre: "/logos/France - Ligue 1/AJ Auxerre.png",
  as_monaco: "/logos/France - Ligue 1/AS Monaco.png",
  angers_sco: "/logos/France - Ligue 1/Angers SCO.png",
  fc_lorient: "/logos/France - Ligue 1/FC Lorient.png",
  fc_metz: "/logos/France - Ligue 1/FC Metz.png",
  fc_nantes: "/logos/France - Ligue 1/FC Nantes.png",
  fc_toulouse: "/logos/France - Ligue 1/FC Toulouse.png",
  losc_lille: "/logos/France - Ligue 1/LOSC Lille.png",
  le_havre_ac: "/logos/France - Ligue 1/Le Havre AC.png",
  ogc_nice: "/logos/France - Ligue 1/OGC Nice.png",
  olympique_lyon: "/logos/France - Ligue 1/Olympique Lyon.png",
  olympique_marseille: "/logos/France - Ligue 1/Olympique Marseille.png",
  paris_fc: "/logos/France - Ligue 1/Paris FC.png",
  paris_saint_germain: "/logos/France - Ligue 1/Paris Saint-Germain.png",
  rc_lens: "/logos/France - Ligue 1/RC Lens.png",
  rc_strasbourg_alsace: "/logos/France - Ligue 1/RC Strasbourg Alsace.png",
  stade_brestois_29: "/logos/France - Ligue 1/Stade Brestois 29.png",
  stade_rennais_fc: "/logos/France - Ligue 1/Stade Rennais FC.png",
  "1_fc_heidenheim_1846": "/logos/Germany - Bundesliga/1.FC Heidenheim 1846.png",
  "1_fc_koln": "/logos/Germany - Bundesliga/1.FC Köln.png",
  "1_fc_union_berlin": "/logos/Germany - Bundesliga/1.FC Union Berlin.png",
  "1_fsv_mainz_05": "/logos/Germany - Bundesliga/1.FSV Mainz 05.png",
  bayer_04_leverkusen: "/logos/Germany - Bundesliga/Bayer 04 Leverkusen.png",
  bayern_munich: "/logos/Germany - Bundesliga/Bayern Munich.png",
  borussia_dortmund: "/logos/Germany - Bundesliga/Borussia Dortmund.png",
  borussia_monchengladbach: "/logos/Germany - Bundesliga/Borussia Mönchengladbach.png",
  eintracht_frankfurt: "/logos/Germany - Bundesliga/Eintracht Frankfurt.png",
  fc_augsburg: "/logos/Germany - Bundesliga/FC Augsburg.png",
  fc_st_pauli: "/logos/Germany - Bundesliga/FC St. Pauli.png",
  hamburger_sv: "/logos/Germany - Bundesliga/Hamburger SV.png",
  rb_leipzig: "/logos/Germany - Bundesliga/RB Leipzig.png",
  sc_freiburg: "/logos/Germany - Bundesliga/SC Freiburg.png",
  sv_werder_bremen: "/logos/Germany - Bundesliga/SV Werder Bremen.png",
  tsg_1899_hoffenheim: "/logos/Germany - Bundesliga/TSG 1899 Hoffenheim.png",
  vfb_stuttgart: "/logos/Germany - Bundesliga/VfB Stuttgart.png",
  vfl_wolfsburg: "/logos/Germany - Bundesliga/VfL Wolfsburg.png",
  ae_kifisias: "/logos/Greece - Super League 1/AE Kifisias.png",
  ae_larisa: "/logos/Greece - Super League 1/AE Larisa.png",
  aek_athens: "/logos/Greece - Super League 1/AEK Athens.png",
  apo_levadiakos: "/logos/Greece - Super League 1/APO Levadiakos.png",
  aris_thessaloniki: "/logos/Greece - Super League 1/Aris Thessaloniki.png",
  asteras_aktor: "/logos/Greece - Super League 1/Asteras Aktor.png",
  atromitos_athens: "/logos/Greece - Super League 1/Atromitos Athens.png",
  ofi_crete_fc: "/logos/Greece - Super League 1/OFI Crete FC.png",
  olympiacos_piraeus: "/logos/Greece - Super League 1/Olympiacos Piraeus.png",
  paok_thessaloniki: "/logos/Greece - Super League 1/PAOK Thessaloniki.png",
  panathinaikos_fc: "/logos/Greece - Super League 1/Panathinaikos FC.png",
  panetolikos_gfs: "/logos/Greece - Super League 1/Panetolikos GFS.png",
  panserraikos: "/logos/Greece - Super League 1/Panserraikos.png",
  volos_nps: "/logos/Greece - Super League 1/Volos NPS.png",
  beitar_jerusalem: "/logos/Israel - Ligat ha'Al/Beitar Jerusalem.png",
  fc_ashdod: "/logos/Israel - Ligat ha'Al/FC Ashdod.png",
  hapoel_beer_sheva: "/logos/Israel - Ligat ha'Al/Hapoel Beer Sheva.png",
  hapoel_haifa: "/logos/Israel - Ligat ha'Al/Hapoel Haifa.png",
  hapoel_jerusalem: "/logos/Israel - Ligat ha'Al/Hapoel Jerusalem.png",
  hapoel_petah_tikva: "/logos/Israel - Ligat ha'Al/Hapoel Petah Tikva.png",
  hapoel_tel_aviv: "/logos/Israel - Ligat ha'Al/Hapoel Tel Aviv.png",
  ihud_bnei_sakhnin: "/logos/Israel - Ligat ha'Al/Ihud Bnei Sakhnin.png",
  ironi_kiryat_shmona: "/logos/Israel - Ligat ha'Al/Ironi Kiryat Shmona.png",
  ironi_tiberias: "/logos/Israel - Ligat ha'Al/Ironi Tiberias.png",
  maccabi_bnei_reineh: "/logos/Israel - Ligat ha'Al/Maccabi Bnei Reineh.png",
  maccabi_haifa: "/logos/Israel - Ligat ha'Al/Maccabi Haifa.png",
  maccabi_netanya: "/logos/Israel - Ligat ha'Al/Maccabi Netanya.png",
  maccabi_tel_aviv: "/logos/Israel - Ligat ha'Al/Maccabi Tel Aviv.png",
  ac_milan: "/logos/Italy - Serie A/AC Milan.png",
  acf_fiorentina: "/logos/Italy - Serie A/ACF Fiorentina.png",
  as_roma: "/logos/Italy - Serie A/AS Roma.png",
  atalanta_bc: "/logos/Italy - Serie A/Atalanta BC.png",
  bologna_fc_1909: "/logos/Italy - Serie A/Bologna FC 1909.png",
  cagliari_calcio: "/logos/Italy - Serie A/Cagliari Calcio.png",
  como_1907: "/logos/Italy - Serie A/Como 1907.png",
  genoa_cfc: "/logos/Italy - Serie A/Genoa CFC.png",
  hellas_verona: "/logos/Italy - Serie A/Hellas Verona.png",
  inter_milan: "/logos/Italy - Serie A/Inter Milan.png",
  juventus_fc: "/logos/Italy - Serie A/Juventus FC.png",
  parma_calcio_1913: "/logos/Italy - Serie A/Parma Calcio 1913.png",
  pisa_sporting_club: "/logos/Italy - Serie A/Pisa Sporting Club.png",
  ss_lazio: "/logos/Italy - Serie A/SS Lazio.png",
  ssc_napoli: "/logos/Italy - Serie A/SSC Napoli.png",
  torino_fc: "/logos/Italy - Serie A/Torino FC.png",
  us_cremonese: "/logos/Italy - Serie A/US Cremonese.png",
  us_lecce: "/logos/Italy - Serie A/US Lecce.png",
  us_sassuolo: "/logos/Italy - Serie A/US Sassuolo.png",
  udinese_calcio: "/logos/Italy - Serie A/Udinese Calcio.png",
  az_alkmaar: "/logos/Netherlands - Eredivisie/AZ Alkmaar.png",
  ajax_amsterdam: "/logos/Netherlands - Eredivisie/Ajax Amsterdam.png",
  excelsior_rotterdam: "/logos/Netherlands - Eredivisie/Excelsior Rotterdam.png",
  fc_groningen: "/logos/Netherlands - Eredivisie/FC Groningen.png",
  fc_utrecht: "/logos/Netherlands - Eredivisie/FC Utrecht.png",
  fc_volendam: "/logos/Netherlands - Eredivisie/FC Volendam.png",
  feyenoord_rotterdam: "/logos/Netherlands - Eredivisie/Feyenoord Rotterdam.png",
  fortuna_sittard: "/logos/Netherlands - Eredivisie/Fortuna Sittard.png",
  go_ahead_eagles: "/logos/Netherlands - Eredivisie/Go Ahead Eagles.png",
  heracles_almelo: "/logos/Netherlands - Eredivisie/Heracles Almelo.png",
  nac_breda: "/logos/Netherlands - Eredivisie/NAC Breda.png",
  nec_nijmegen: "/logos/Netherlands - Eredivisie/NEC Nijmegen.png",
  pec_zwolle: "/logos/Netherlands - Eredivisie/PEC Zwolle.png",
  psv_eindhoven: "/logos/Netherlands - Eredivisie/PSV Eindhoven.png",
  sc_heerenveen: "/logos/Netherlands - Eredivisie/SC Heerenveen.png",
  sc_telstar: "/logos/Netherlands - Eredivisie/SC Telstar.png",
  sparta_rotterdam: "/logos/Netherlands - Eredivisie/Sparta Rotterdam.png",
  twente_enschede_fc: "/logos/Netherlands - Eredivisie/Twente Enschede FC.png",
  bryne_fk: "/logos/Norway - Eliteserien/Bryne FK.png",
  fk_bod_glimt: "/logos/Norway - Eliteserien/FK BodøGlimt.png",
  fk_haugesund: "/logos/Norway - Eliteserien/FK Haugesund.png",
  fredrikstad_fk: "/logos/Norway - Eliteserien/Fredrikstad FK.png",
  hamarkameratene: "/logos/Norway - Eliteserien/Hamarkameratene.png",
  kfum_kameratene_oslo: "/logos/Norway - Eliteserien/KFUM-Kameratene Oslo.png",
  kristiansund_bk: "/logos/Norway - Eliteserien/Kristiansund BK.png",
  molde_fk: "/logos/Norway - Eliteserien/Molde FK.png",
  rosenborg_bk: "/logos/Norway - Eliteserien/Rosenborg BK.png",
  sk_brann: "/logos/Norway - Eliteserien/SK Brann.png",
  sandefjord_fotball: "/logos/Norway - Eliteserien/Sandefjord Fotball.png",
  sarpsborg_08_ff: "/logos/Norway - Eliteserien/Sarpsborg 08 FF.png",
  stromsgodset_if: "/logos/Norway - Eliteserien/Strømsgodset IF.png",
  tromso_il: "/logos/Norway - Eliteserien/Tromsø IL.png",
  viking_fk: "/logos/Norway - Eliteserien/Viking FK.png",
  valerenga_fotball_elite: "/logos/Norway - Eliteserien/Vålerenga Fotball Elite.png",
  arka_gdynia: "/logos/Poland - PKO BP Ekstraklasa/Arka Gdynia.png",
  bruk_bet_termalica_nieciecza: "/logos/Poland - PKO BP Ekstraklasa/Bruk-Bet Termalica Nieciecza.png",
  cracovia: "/logos/Poland - PKO BP Ekstraklasa/Cracovia.png",
  gks_katowice: "/logos/Poland - PKO BP Ekstraklasa/GKS Katowice.png",
  gornik_zabrze: "/logos/Poland - PKO BP Ekstraklasa/Górnik Zabrze.png",
  jagiellonia_bialystok: "/logos/Poland - PKO BP Ekstraklasa/Jagiellonia Bialystok.png",
  korona_kielce: "/logos/Poland - PKO BP Ekstraklasa/Korona Kielce.png",
  lech_poznan: "/logos/Poland - PKO BP Ekstraklasa/Lech Poznan.png",
  lechia_gdansk: "/logos/Poland - PKO BP Ekstraklasa/Lechia Gdansk.png",
  legia_warszawa: "/logos/Poland - PKO BP Ekstraklasa/Legia Warszawa.png",
  motor_lublin: "/logos/Poland - PKO BP Ekstraklasa/Motor Lublin.png",
  piast_gliwice: "/logos/Poland - PKO BP Ekstraklasa/Piast Gliwice.png",
  pogon_szczecin: "/logos/Poland - PKO BP Ekstraklasa/Pogon Szczecin.png",
  radomiak_radom: "/logos/Poland - PKO BP Ekstraklasa/Radomiak Radom.png",
  rakow_czestochowa: "/logos/Poland - PKO BP Ekstraklasa/Raków Częstochowa.png",
  widzew_lodz: "/logos/Poland - PKO BP Ekstraklasa/Widzew Lodz.png",
  wisla_plock: "/logos/Poland - PKO BP Ekstraklasa/Wisla Plock.png",
  zaglebie_lubin: "/logos/Poland - PKO BP Ekstraklasa/Zaglebie Lubin.png",
  avs_futebol: "/logos/Portugal - Liga Portugal/Avs Futebol.png",
  cd_nacional: "/logos/Portugal - Liga Portugal/CD Nacional.png",
  cd_santa_clara: "/logos/Portugal - Liga Portugal/CD Santa Clara.png",
  cd_tondela: "/logos/Portugal - Liga Portugal/CD Tondela.png",
  cf_estrela_amadora: "/logos/Portugal - Liga Portugal/CF Estrela Amadora.png",
  casa_pia_ac: "/logos/Portugal - Liga Portugal/Casa Pia AC.png",
  fc_alverca: "/logos/Portugal - Liga Portugal/FC Alverca.png",
  fc_arouca: "/logos/Portugal - Liga Portugal/FC Arouca.png",
  fc_famalicao: "/logos/Portugal - Liga Portugal/FC Famalicão.png",
  fc_porto: "/logos/Portugal - Liga Portugal/FC Porto.png",
  gd_estoril_praia: "/logos/Portugal - Liga Portugal/GD Estoril Praia.png",
  gil_vicente_fc: "/logos/Portugal - Liga Portugal/Gil Vicente FC.png",
  moreirense_fc: "/logos/Portugal - Liga Portugal/Moreirense FC.png",
  rio_ave_fc: "/logos/Portugal - Liga Portugal/Rio Ave FC.png",
  sc_braga: "/logos/Portugal - Liga Portugal/SC Braga.png",
  sl_benfica: "/logos/Portugal - Liga Portugal/SL Benfica.png",
  sporting_cp: "/logos/Portugal - Liga Portugal/Sporting CP.png",
  vitoria_guimaraes_sc: "/logos/Portugal - Liga Portugal/Vitória Guimarães SC.png",
  acsc_fc_arges: "/logos/Romania - SuperLiga/ACSC FC Arges.png",
  afc_unirea_04_slobozia: "/logos/Romania - SuperLiga/AFC Unirea 04 Slobozia.png",
  afk_csikszereda_miercurea_ciuc: "/logos/Romania - SuperLiga/AFK Csikszereda Miercurea Ciuc.png",
  cfr_cluj: "/logos/Romania - SuperLiga/CFR Cluj.png",
  cs_universitatea_craiova: "/logos/Romania - SuperLiga/CS Universitatea Craiova.png",
  fc_botosani: "/logos/Romania - SuperLiga/FC Botosani.png",
  fc_dinamo_1948: "/logos/Romania - SuperLiga/FC Dinamo 1948.png",
  fc_hermannstadt: "/logos/Romania - SuperLiga/FC Hermannstadt.png",
  fc_metaloglobus_bucharest: "/logos/Romania - SuperLiga/FC Metaloglobus Bucharest.png",
  fc_rapid_1923: "/logos/Romania - SuperLiga/FC Rapid 1923.png",
  fc_universitatea_cluj: "/logos/Romania - SuperLiga/FC Universitatea Cluj.png",
  fcsb: "/logos/Romania - SuperLiga/FCSB.png",
  fcv_farul_constanta: "/logos/Romania - SuperLiga/FCV Farul Constanta.png",
  petrolul_ploiesti: "/logos/Romania - SuperLiga/Petrolul Ploiesti.png",
  sc_otelul_galati: "/logos/Romania - SuperLiga/SC Otelul Galati.png",
  uta_arad: "/logos/Romania - SuperLiga/UTA Arad.png",
  akhmat_grozny: "/logos/Russia - Premier Liga/Akhmat Grozny.png",
  akron_togliatti: "/logos/Russia - Premier Liga/Akron Togliatti.png",
  baltika_kaliningrad: "/logos/Russia - Premier Liga/Baltika Kaliningrad.png",
  cska_moscow: "/logos/Russia - Premier Liga/CSKA Moscow.png",
  dinamo_makhachkala: "/logos/Russia - Premier Liga/Dinamo Makhachkala.png",
  dynamo_moscow: "/logos/Russia - Premier Liga/Dynamo Moscow.png",
  fc_krasnodar: "/logos/Russia - Premier Liga/FC Krasnodar.png",
  fc_pari_nizhniy_novgorod: "/logos/Russia - Premier Liga/FC Pari Nizhniy Novgorod.png",
  fc_rostov: "/logos/Russia - Premier Liga/FC Rostov.png",
  fc_sochi: "/logos/Russia - Premier Liga/FC Sochi.png",
  krylya_sovetov_samara: "/logos/Russia - Premier Liga/Krylya Sovetov Samara.png",
  lokomotiv_moscow: "/logos/Russia - Premier Liga/Lokomotiv Moscow.png",
  rubin_kazan: "/logos/Russia - Premier Liga/Rubin Kazan.png",
  spartak_moscow: "/logos/Russia - Premier Liga/Spartak Moscow.png",
  torpedo_moscow: "/logos/Russia - Premier Liga/Torpedo Moscow.png",
  zenit_st_petersburg: "/logos/Russia - Premier Liga/Zenit St. Petersburg.png",
  aberdeen_fc: "/logos/Scotland - Scottish Premiership/Aberdeen FC.png",
  celtic_fc: "/logos/Scotland - Scottish Premiership/Celtic FC.png",
  dundee_fc: "/logos/Scotland - Scottish Premiership/Dundee FC.png",
  dundee_united_fc: "/logos/Scotland - Scottish Premiership/Dundee United FC.png",
  falkirk_fc: "/logos/Scotland - Scottish Premiership/Falkirk FC.png",
  heart_of_midlothian_fc: "/logos/Scotland - Scottish Premiership/Heart of Midlothian FC.png",
  hibernian_fc: "/logos/Scotland - Scottish Premiership/Hibernian FC.png",
  kilmarnock_fc: "/logos/Scotland - Scottish Premiership/Kilmarnock FC.png",
  livingston_fc: "/logos/Scotland - Scottish Premiership/Livingston FC.png",
  motherwell_fc: "/logos/Scotland - Scottish Premiership/Motherwell FC.png",
  rangers_fc: "/logos/Scotland - Scottish Premiership/Rangers FC.png",
  st_mirren_fc: "/logos/Scotland - Scottish Premiership/St. Mirren FC.png",
  fk_cukaricki: "/logos/Serbia - Super liga Srbije/FK Cukaricki.png",
  fk_imt_belgrad: "/logos/Serbia - Super liga Srbije/FK IMT Belgrad.png",
  fk_javor_matis_ivanjica: "/logos/Serbia - Super liga Srbije/FK Javor-Matis Ivanjica.png",
  fk_mladost_lucani: "/logos/Serbia - Super liga Srbije/FK Mladost Lucani.png",
  fk_napredak_krusevac: "/logos/Serbia - Super liga Srbije/FK Napredak Krusevac.png",
  fk_novi_pazar: "/logos/Serbia - Super liga Srbije/FK Novi Pazar.png",
  fk_partizan_belgrade: "/logos/Serbia - Super liga Srbije/FK Partizan Belgrade.png",
  fk_radnicki_1923_kragujevac: "/logos/Serbia - Super liga Srbije/FK Radnicki 1923 Kragujevac.png",
  fk_radnicki_nis: "/logos/Serbia - Super liga Srbije/FK Radnicki Nis.png",
  fk_radnik_surdulica: "/logos/Serbia - Super liga Srbije/FK Radnik Surdulica.png",
  fk_spartak_subotica: "/logos/Serbia - Super liga Srbije/FK Spartak Subotica.png",
  fk_tsc_backa_topola: "/logos/Serbia - Super liga Srbije/FK TSC Backa Topola.png",
  fk_vojvodina_novi_sad: "/logos/Serbia - Super liga Srbije/FK Vojvodina Novi Sad.png",
  ofk_beograd: "/logos/Serbia - Super liga Srbije/OFK Beograd.png",
  red_star_belgrade: "/logos/Serbia - Super liga Srbije/Red Star Belgrade.png",
  zeleznicar_pancevo: "/logos/Serbia - Super liga Srbije/Zeleznicar Pancevo.png",
  athletic_bilbao: "/logos/Spain - LaLiga/Athletic Bilbao.png",
  atletico_de_madrid: "/logos/Spain - LaLiga/Atlético de Madrid.png",
  ca_osasuna: "/logos/Spain - LaLiga/CA Osasuna.png",
  celta_de_vigo: "/logos/Spain - LaLiga/Celta de Vigo.png",
  deportivo_alaves: "/logos/Spain - LaLiga/Deportivo Alavés.png",
  elche_cf: "/logos/Spain - LaLiga/Elche CF.png",
  fc_barcelona: "/logos/Spain - LaLiga/FC Barcelona.png",
  getafe_cf: "/logos/Spain - LaLiga/Getafe CF.png",
  girona_fc: "/logos/Spain - LaLiga/Girona FC.png",
  levante_ud: "/logos/Spain - LaLiga/Levante UD.png",
  rcd_espanyol_barcelona: "/logos/Spain - LaLiga/RCD Espanyol Barcelona.png",
  rcd_mallorca: "/logos/Spain - LaLiga/RCD Mallorca.png",
  rayo_vallecano: "/logos/Spain - LaLiga/Rayo Vallecano.png",
  real_betis_balompie: "/logos/Spain - LaLiga/Real Betis Balompié.png",
  real_madrid: "/logos/Spain - LaLiga/Real Madrid.png",
  real_oviedo: "/logos/Spain - LaLiga/Real Oviedo.png",
  real_sociedad: "/logos/Spain - LaLiga/Real Sociedad.png",
  sevilla_fc: "/logos/Spain - LaLiga/Sevilla FC.png",
  valencia_cf: "/logos/Spain - LaLiga/Valencia CF.png",
  villarreal_cf: "/logos/Spain - LaLiga/Villarreal CF.png",
  aik: "/logos/Sweden - Allsvenskan/AIK.png",
  bk_hacken: "/logos/Sweden - Allsvenskan/BK Häcken.png",
  degerfors_if: "/logos/Sweden - Allsvenskan/Degerfors IF.png",
  djurgardens_if: "/logos/Sweden - Allsvenskan/Djurgårdens IF.png",
  gais: "/logos/Sweden - Allsvenskan/GAIS.png",
  halmstads_bk: "/logos/Sweden - Allsvenskan/Halmstads BK.png",
  hammarby_if: "/logos/Sweden - Allsvenskan/Hammarby IF.png",
  if_brommapojkarna: "/logos/Sweden - Allsvenskan/IF Brommapojkarna.png",
  if_elfsborg: "/logos/Sweden - Allsvenskan/IF Elfsborg.png",
  ifk_goteborg: "/logos/Sweden - Allsvenskan/IFK Göteborg.png",
  ifk_norrkoping: "/logos/Sweden - Allsvenskan/IFK Norrköping.png",
  ifk_varnamo: "/logos/Sweden - Allsvenskan/IFK Värnamo.png",
  ik_sirius: "/logos/Sweden - Allsvenskan/IK Sirius.png",
  malmo_ff: "/logos/Sweden - Allsvenskan/Malmö FF.png",
  mjallby_aif: "/logos/Sweden - Allsvenskan/Mjällby AIF.png",
  osters_if: "/logos/Sweden - Allsvenskan/Östers IF.png",
  bsc_young_boys: "/logos/Switzerland - Super League/BSC Young Boys.png",
  fc_basel_1893: "/logos/Switzerland - Super League/FC Basel 1893.png",
  fc_lausanne_sport: "/logos/Switzerland - Super League/FC Lausanne-Sport.png",
  fc_lugano: "/logos/Switzerland - Super League/FC Lugano.png",
  fc_luzern: "/logos/Switzerland - Super League/FC Luzern.png",
  fc_sion: "/logos/Switzerland - Super League/FC Sion.png",
  fc_st_gallen_1879: "/logos/Switzerland - Super League/FC St. Gallen 1879.png",
  fc_thun: "/logos/Switzerland - Super League/FC Thun.png",
  fc_winterthur: "/logos/Switzerland - Super League/FC Winterthur.png",
  fc_zurich: "/logos/Switzerland - Super League/FC Zürich.png",
  grasshopper_club_zurich: "/logos/Switzerland - Super League/Grasshopper Club Zurich.png",
  servette_fc: "/logos/Switzerland - Super League/Servette FC.png",
  alanyaspor: "/logos/Türkiye - Süper Lig/Alanyaspor.png",
  antalyaspor: "/logos/Türkiye - Süper Lig/Antalyaspor.png",
  basaksehir_fk: "/logos/Türkiye - Süper Lig/Basaksehir FK.png",
  besiktas_jk: "/logos/Türkiye - Süper Lig/Besiktas JK.png",
  caykur_rizespor: "/logos/Türkiye - Süper Lig/Caykur Rizespor.png",
  eyupspor: "/logos/Türkiye - Süper Lig/Eyüpspor.png",
  fatih_karagumruk: "/logos/Türkiye - Süper Lig/Fatih Karagümrük.png",
  fenerbahce: "/logos/Türkiye - Süper Lig/Fenerbahce.png",
  galatasaray: "/logos/Türkiye - Süper Lig/Galatasaray.png",
  gaziantep_fk: "/logos/Türkiye - Süper Lig/Gaziantep FK.png",
  genclerbirligi_ankara: "/logos/Türkiye - Süper Lig/Genclerbirligi Ankara.png",
  goztepe: "/logos/Türkiye - Süper Lig/Göztepe.png",
  kasimpasa: "/logos/Türkiye - Süper Lig/Kasimpasa.png",
  kayserispor: "/logos/Türkiye - Süper Lig/Kayserispor.png",
  kocaelispor: "/logos/Türkiye - Süper Lig/Kocaelispor.png",
  konyaspor: "/logos/Türkiye - Süper Lig/Konyaspor.png",
  samsunspor: "/logos/Türkiye - Süper Lig/Samsunspor.png",
  trabzonspor: "/logos/Türkiye - Süper Lig/Trabzonspor.png",
  dynamo_kyiv: "/logos/Ukraine - Premier Liga/Dynamo Kyiv.png",
  epicentr_kamyanets_podilskyi: "/logos/Ukraine - Premier Liga/Epicentr Kamyanets-Podilskyi.png",
  fc_kudrivka: "/logos/Ukraine - Premier Liga/FC Kudrivka.png",
  fc_oleksandriya: "/logos/Ukraine - Premier Liga/FC Oleksandriya.png",
  karpaty_lviv: "/logos/Ukraine - Premier Liga/Karpaty Lviv.png",
  kolos_kovalivka: "/logos/Ukraine - Premier Liga/Kolos Kovalivka.png",
  kryvbas_kryvyi_rig: "/logos/Ukraine - Premier Liga/Kryvbas Kryvyi Rig.png",
  lnz_cherkasy: "/logos/Ukraine - Premier Liga/LNZ Cherkasy.png",
  metalist_1925_kharkiv: "/logos/Ukraine - Premier Liga/Metalist 1925 Kharkiv.png",
  nk_veres_rivne: "/logos/Ukraine - Premier Liga/NK Veres Rivne.png",
  obolon_kyiv: "/logos/Ukraine - Premier Liga/Obolon Kyiv.png",
  polissya_zhytomyr: "/logos/Ukraine - Premier Liga/Polissya Zhytomyr.png",
  rukh_lviv: "/logos/Ukraine - Premier Liga/Rukh Lviv.png",
  sc_poltava: "/logos/Ukraine - Premier Liga/SC Poltava.png",
  shakhtar_donetsk: "/logos/Ukraine - Premier Liga/Shakhtar Donetsk.png",
  zorya_lugansk: "/logos/Ukraine - Premier Liga/Zorya Lugansk.png",
};

const CLUB_LOGO_ALIASES = {
  arsenal: "arsenal_fc",
  villa: "aston_villa",
  bournemouth: "afc_bournemouth",
  brighton: "brighton_and_hove_albion",
  burnley: "burnley_fc",
  chelsea: "chelsea_fc",
  everton: "everton_fc",
  fulham: "fulham_fc",
  liverpool: "liverpool_fc",
  city: "manchester_city",
  man_city: "manchester_city",
  mcfc: "manchester_city",
  united: "manchester_united",
  man_utd: "manchester_united",
  man_u: "manchester_united",
  mufc: "manchester_united",
  newcastle: "newcastle_united",
  spurs: "tottenham_hotspur",
  tottenham: "tottenham_hotspur",
  west_ham: "west_ham_united",
  wolves: "wolverhampton_wanderers",
  psg: "paris_saint_germain",
  lyon: "olympique_lyon",
  marseille: "olympique_marseille",
  monaco: "as_monaco",
  dortmund: "borussia_dortmund",
  gladbach: "borussia_monchengladbach",
  bayern: "bayern_munich",
  leverkusen: "bayer_04_leverkusen",
  leipzig: "rb_leipzig",
  inter: "inter_milan",
  milan: "ac_milan",
  juve: "juventus_fc",
  juventus: "juventus_fc",
  roma: "as_roma",
  lazio: "ss_lazio",
  napoli: "ssc_napoli",
  barca: "fc_barcelona",
  fcb: "fc_barcelona",
  barcelona: "fc_barcelona",
  real: "real_madrid",
  real_madrid_cf: "real_madrid",
  madrid: "real_madrid",
  rma: "real_madrid",
  atletico: "atletico_de_madrid",
  atleti: "atletico_de_madrid",
  sevilla: "sevilla_fc",
  betis: "real_betis_balompie",
  sociedad: "real_sociedad",
  bilbao: "athletic_bilbao",
  porto: "fc_porto",
  benfica: "sl_benfica",
  sporting: "sporting_cp",
  sporting_lisbon: "sporting_cp",
  ajax: "ajax_amsterdam",
  psv: "psv_eindhoven",
  feyenoord: "feyenoord_rotterdam",
  celtic: "celtic_fc",
  rangers: "rangers_fc",
};

const STRIP_TOKENS = new Set([
  "fc",
  "cf",
  "sc",
  "ac",
  "afc",
  "cfc",
  "fk",
  "sk",
  "nk",
  "if",
  "bk",
  "ff",
  "kv",
  "vv",
  "jk",
  "bc",
  "ud",
  "cd",
  "gd",
  "sl",
  "ss",
  "us",
  "rc",
  "ogc",
  "losc",
  "psv",
]);

function normalizeTeamName(value) {
  return String(value || "")
    .trim()
    .toLowerCase()
    .normalize("NFD")
    .replace(/[\u0300-\u036f]/g, "")
    .replace(/&/g, " and ")
    .replace(/[^a-z0-9]+/g, "_")
    .replace(/^_+|_+$/g, "");
}

function stripTokens(normalized) {
  return normalized
    .split("_")
    .filter((token) => token && !STRIP_TOKENS.has(token))
    .join("_");
}

const CLUB_LOGO_BY_STRIPPED_NAME = Object.fromEntries(
  Object.entries(CLUB_LOGO_BY_NAME).map(([name, path]) => [stripTokens(name), path]),
);

export function getClubLogoUrl(teamName) {
  const normalized = normalizeTeamName(teamName);
  if (!normalized) return null;
  const aliasTarget = CLUB_LOGO_ALIASES[normalized];
  return (
    (aliasTarget ? CLUB_LOGO_BY_NAME[aliasTarget] : null) ||
    CLUB_LOGO_BY_NAME[normalized] ||
    CLUB_LOGO_BY_STRIPPED_NAME[normalized] ||
    CLUB_LOGO_BY_STRIPPED_NAME[stripTokens(normalized)] ||
    null
  );
}

export function getTeamLogoUrl(teamName) {
  return getClubLogoUrl(teamName) || getCountryFlagUrl(teamName);
}

export function formatTeamDisplayName(teamName) {
  const value = String(teamName || "").trim();
  if (!value) return "";
  if (/^[A-Za-z0-9]{2,5}$/.test(value.replace(/\s+/g, ""))) {
    return value.toUpperCase();
  }

  return value
    .toLowerCase()
    .split(/\s+/)
    .map((word) => {
      if (/^[a-z]{2,5}$/.test(word) && word === word.toUpperCase()) {
        return word.toUpperCase();
      }
      return word.charAt(0).toUpperCase() + word.slice(1);
    })
    .join(" ")
    .replace(/\bFc\b/g, "FC")
    .replace(/\bCf\b/g, "CF")
    .replace(/\bSc\b/g, "SC")
    .replace(/\bAc\b/g, "AC")
    .replace(/\bAfc\b/g, "AFC")
    .replace(/\bRb\b/g, "RB")
    .replace(/\bPsg\b/g, "PSG")
    .replace(/\bPsv\b/g, "PSV")
    .replace(/\bAik\b/g, "AIK")
    .replace(/\bIfk\b/g, "IFK");
}
